"""
Script:       demo.py
Library:      lib_bejson_markdown (Lib_MD)
Jurisdiction: ["BEJSON_LIBRARIES", "PY"]
Author:       Elton Boehnen
Version:      1.0.0
Date:         2026-06-15
Description:  End-to-end demonstration of lib_bejson_markdown.
              Demonstrates: indexing, pull, inject, toggle, assemble,
              and the MFDB multi-file database workflow.
              Run from the Lib_MD_v1/ directory.
RELATIONAL_ID: md-lib-demo-20260615-001
"""

import os
import sys
import json
import shutil
import tempfile
from pathlib import Path

# ---------------------------------------------------------------------------
# Path setup — ensure lib/ is on sys.path so Core libs are found
# ---------------------------------------------------------------------------

SCRIPT_PATH = Path(__file__).resolve().parent
LIB_PATH    = SCRIPT_PATH / "lib"
if str(LIB_PATH) not in sys.path:
    sys.path.insert(0, str(LIB_PATH))
if str(SCRIPT_PATH) not in sys.path:
    sys.path.insert(0, str(SCRIPT_PATH))

VERSION = "1.0.0"

# ---------------------------------------------------------------------------
# Attempt imports — fail with a clear message if Core is missing
# ---------------------------------------------------------------------------

try:
    from lib_md_indexer import (
        md_indexer_build_index_doc,
        md_indexer_reindex_file,
        md_indexer_list_chunks,
        md_indexer_save_index,
    )
    from lib_md_ops import (
        md_ops_pull,
        md_ops_inject,
        md_ops_toggle,
        md_ops_toggle_by_tag,
        md_ops_set_tags,
        md_ops_set_sort_order,
        md_ops_assemble,
        md_ops_assemble_by_tag,
        md_ops_list_chunks,
        md_ops_reindex,
    )
    from lib_md_db import (
        md_db_create,
        md_db_exists,
        md_db_register_file,
        md_db_list_files,
        md_db_list_chunks,
        md_db_toggle,
        md_db_set_tags,
        md_db_assemble_by_tag,
        md_db_reindex_all,
    )
    from lib_md_errors import (
        ChunkDriftError,
        AssembleEmptyError,
        ChunkNotFoundError,
    )
except ImportError as e:
    print(f"\n[demo] Import failed: {e}")
    print("Copy Lib_PY/Core/*.py files into Lib_MD_v1/lib/ then re-run.\n")
    sys.exit(1)

# ---------------------------------------------------------------------------
# ANSI helpers
# ---------------------------------------------------------------------------

C_RED   = "\033[91m"
C_GREEN = "\033[92m"
C_CYAN  = "\033[96m"
C_BOLD  = "\033[1m"
C_NC    = "\033[0m"

def ok(msg):  print(f"  {C_GREEN}✓{C_NC} {msg}")
def err(msg): print(f"  {C_RED}✗{C_NC} {msg}")
def hdr(msg): print(f"\n{C_BOLD}{C_CYAN}{'─' * 60}{C_NC}")
def log(msg): print(f"    {msg}")


# ---------------------------------------------------------------------------
# Sample markdown content
# ---------------------------------------------------------------------------

SAMPLE_MD = """---
title: Demo Policy Document
version: 1.0.0
---

# Introduction

This is the introduction section. It describes the purpose of this policy set.

## Core Directives

Always be helpful, accurate, and concise.
Never fabricate information.
Prefer direct answers over lengthy preambles.

## Python Standards

- Use type hints on all function signatures.
- Prefer pathlib over os.path for file operations.
- Use snake_case for all variable and function names.

```python
def get_script_path() -> Path:
    return Path(__file__).resolve().parent

SCRIPT_PATH = get_script_path()
```

## Code Review Policy

When reviewing code:
1. Check for obvious bugs first.
2. Verify error handling is present.
3. Confirm the code matches the stated intent.

# Footer

Generated by lib_bejson_markdown v1.0.0.
"""

SAMPLE_MD_2 = """# Writing Guidelines

Keep sentences short.
Use active voice.
Define technical terms on first use.

## Style Rules

- No more than 3 levels of nesting.
- Headings use title case.
- Code blocks must specify language.
"""


# ---------------------------------------------------------------------------
# Demo runner
# ---------------------------------------------------------------------------

def main():
    print(f"\n{C_BOLD}lib_bejson_markdown — Demo v{VERSION}{C_NC}")
    print(f"{'=' * 60}\n")

    tmp = tempfile.mkdtemp(prefix="libmd_demo_")
    try:
        _run_demo(tmp)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
        print(f"\n{C_BOLD}Demo workspace cleaned up.{C_NC}")


def _run_demo(tmp: str):
    # -----------------------------------------------------------------------
    # PART 1 — Single-file workflow
    # -----------------------------------------------------------------------
    hdr("PART 1 — Single-file Indexer + Operations")
    print(f"\n  {C_BOLD}[1/8] Write sample markdown file{C_NC}")

    md_file    = os.path.join(tmp, "policy.md")
    index_file = os.path.join(tmp, "policy.chunk_index.bejson")

    Path(md_file).write_text(SAMPLE_MD, encoding="utf-8")
    ok(f"Written: {md_file}")

    # -----------------------------------------------------------------------
    print(f"\n  {C_BOLD}[2/8] Index the file{C_NC}")

    doc = md_indexer_build_index_doc(md_file)
    md_indexer_save_index(doc, index_file)
    chunks = md_indexer_list_chunks(doc)
    ok(f"Found {len(chunks)} chunks")

    for c in chunks:
        log(f"  [{c['chunk_type']:<12}] L{c['start_line']:>3}–{c['end_line']:<3}  {c['label'][:50]}")

    # -----------------------------------------------------------------------
    print(f"\n  {C_BOLD}[3/8] Tag chunks and set sort order{C_NC}")

    # Find chunks by type for tagging
    heading_chunks = [c for c in chunks if c["chunk_type"] == "heading"]
    raw_chunks     = [c for c in chunks if c["chunk_type"] == "raw"]
    code_chunks    = [c for c in chunks if c["chunk_type"] == "code_block"]

    # Tag all heading chunks as "structure"
    for c in heading_chunks:
        md_ops_set_tags(index_file, c["chunk_id"], ["structure", "system_context"])
        ok(f"Tagged heading '{c['label'][:40]}' → [structure, system_context]")

    # Tag raw chunks as "policy"
    for i, c in enumerate(raw_chunks):
        md_ops_set_tags(index_file, c["chunk_id"], ["policy", "system_context"])
        md_ops_set_sort_order(index_file, c["chunk_id"], i * 10)
        ok(f"Tagged raw chunk L{c['start_line']} → [policy, system_context] order={i*10}")

    # Tag code blocks as "code_example" — NOT included in system context
    for c in code_chunks:
        md_ops_set_tags(index_file, c["chunk_id"], ["code_example"])
        ok(f"Tagged code block L{c['start_line']} → [code_example]")

    # -----------------------------------------------------------------------
    print(f"\n  {C_BOLD}[4/8] Pull a specific chunk{C_NC}")

    if raw_chunks:
        first_raw = raw_chunks[0]
        content   = md_ops_pull(index_file, first_raw["chunk_id"])
        ok(f"Pulled chunk '{first_raw['chunk_id']}'")
        log(f"Content preview: {repr(content[:80])}...")

    # -----------------------------------------------------------------------
    print(f"\n  {C_BOLD}[5/8] Assemble system_context tag{C_NC}")

    try:
        assembled = md_ops_assemble_by_tag(index_file, "system_context")
        ok(f"Assembled {len(assembled)} characters")
        log(f"First 200 chars:\n{assembled[:200]}...")
    except AssembleEmptyError as e:
        err(f"Nothing to assemble: {e}")

    # -----------------------------------------------------------------------
    print(f"\n  {C_BOLD}[6/8] Toggle code_example chunks OFF{C_NC}")

    toggled = md_ops_toggle_by_tag(index_file, "code_example", active=False)
    ok(f"Deactivated {len(toggled)} chunk(s): {toggled}")

    active_chunks = md_ops_list_chunks(index_file, active_only=True)
    ok(f"Active chunks remaining: {len(active_chunks)}")

    # -----------------------------------------------------------------------
    print(f"\n  {C_BOLD}[7/8] Inject new content into a chunk{C_NC}")

    if raw_chunks:
        target    = raw_chunks[-1]
        old_text  = md_ops_pull(index_file, target["chunk_id"], verify_checksum=False)
        new_text  = old_text.rstrip("\n") + "\n- INJECTED: Additional policy rule.\n"
        new_doc   = md_ops_inject(index_file, target["chunk_id"], new_text)
        ok(f"Injected into '{target['chunk_id']}'")
        ok(f"Index rewritten with {len(new_doc.get('Values', []))} chunks after reindex")

        # Verify drift detection is reset
        pulled_back = md_ops_pull(index_file, target["chunk_id"])
        if "INJECTED" in pulled_back:
            ok("Injected content verified in pull — no drift")
        else:
            err("Injected content NOT found in pull")

    # -----------------------------------------------------------------------
    print(f"\n  {C_BOLD}[8/8] Checksum drift detection{C_NC}")

    chunks_now = md_ops_list_chunks(index_file)
    if chunks_now:
        target_chunk = chunks_now[0]
        cid          = target_chunk["chunk_id"]

        # Corrupt the file directly (simulate out-of-band edit)
        content = Path(md_file).read_text(encoding="utf-8")
        Path(md_file).write_text(content + "\n<!-- OUT-OF-BAND EDIT -->\n", encoding="utf-8")

        try:
            md_ops_pull(index_file, cid, verify_checksum=True)
            err("Drift NOT detected — this is a bug")
        except ChunkDriftError as e:
            ok(f"Drift correctly detected: {e}")

        # Reindex to recover
        md_ops_reindex(md_file, index_file)
        ok("Reindex completed — drift cleared")

    # -----------------------------------------------------------------------
    # PART 2 — MFDB multi-file workflow
    # -----------------------------------------------------------------------
    hdr("PART 2 — MFDB Multi-file Database")
    print()

    db_root = os.path.join(tmp, "markdown_db")

    print(f"  {C_BOLD}[A] Create MFDB{C_NC}")
    manifest = md_db_create(db_root, "Demo Policy DB", "lib_bejson_markdown demo")
    ok(f"Created: {manifest}")
    ok(f"DB exists: {md_db_exists(db_root)}")

    print(f"\n  {C_BOLD}[B] Register markdown files{C_NC}")

    md_file_2 = os.path.join(tmp, "writing.md")
    Path(md_file_2).write_text(SAMPLE_MD_2, encoding="utf-8")

    fid1 = md_db_register_file(db_root, md_file,   "Main policy doc",    ["policy"])
    fid2 = md_db_register_file(db_root, md_file_2, "Writing guidelines", ["writing"])
    ok(f"Registered '{fid1}' and '{fid2}'")

    files = md_db_list_files(db_root)
    for f in files:
        ok(f"  {f['file_id']}: {f['chunk_count']} chunks, last indexed {f['last_indexed']}")

    print(f"\n  {C_BOLD}[C] Tag chunks in DB and assemble{C_NC}")

    chunks_1 = md_db_list_chunks(db_root, fid1)
    chunks_2 = md_db_list_chunks(db_root, fid2)

    for c in chunks_1[:3]:
        md_db_set_tags(db_root, fid1, c["chunk_id"], ["gemini_context"])
        ok(f"Tagged {c['chunk_id'][:40]} → [gemini_context]")

    for c in chunks_2[:2]:
        md_db_set_tags(db_root, fid2, c["chunk_id"], ["gemini_context"])
        ok(f"Tagged {c['chunk_id'][:40]} → [gemini_context]")

    try:
        prompt = md_db_assemble_by_tag(db_root, "gemini_context")
        ok(f"Cross-file assembly: {len(prompt)} characters")
        log(f"Preview:\n{prompt[:300]}...")
    except AssembleEmptyError as e:
        err(f"Assembly failed: {e}")

    print(f"\n  {C_BOLD}[D] Toggle a chunk off and verify{C_NC}")

    if chunks_1:
        target_cid = chunks_1[0]["chunk_id"]
        new_state  = md_db_toggle(db_root, fid1, target_cid, active=False)
        ok(f"Toggled '{target_cid[:40]}' → is_active={new_state}")

    print(f"\n  {C_BOLD}[E] Reindex all files{C_NC}")

    results = md_db_reindex_all(db_root)
    for fid, doc in results.items():
        ok(f"  {fid}: {len(doc.get('Values', []))} chunks after reindex")

    # -----------------------------------------------------------------------
    print(f"\n{C_BOLD}{'=' * 60}")
    print(f"All demo steps completed — lib_bejson_markdown v{VERSION}")
    print(f"{'=' * 60}{C_NC}\n")


if __name__ == "__main__":
    main()
